version: '3.1'

services:
  dev_dc:
    container_name: code
    # build: .
    image: binacslee/deployment-code-server
    environment:
      - PASSWORD=password
    volumes:
      # - ./config:/root/.config/code-server:ro
      # - ./extensions:/root/.local/share/code-server/extensions:ro
      # - ./settings:/root/.local/share/code-server/User:ro
      - .:/gitpro
    ports:
      - 10000:8443
